<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('condem', function (Blueprint $table) {
            $table->id('condemID');
            $table->integer('modelID');
            $table->string('Vk 40 min');
            $table->string('Vk 40 max');
            $table->string('Vk 40 border');
            $table->string('Vk 40 per');
            $table->string('Vk 40 ket');
            $table->string('Vk 100 min');
            $table->string('Vk 100 max');
            $table->string('Vk 100 border');
            $table->string('Vk 100 per');
            $table->string('Vk 100 ket');
            $table->string('Oxi min');
            $table->string('Oxi max');
            $table->string('Oxi border');
            $table->string('Oxi per');
            $table->string('Oxi ket');
            $table->string('P min');
            $table->string('P max');
            $table->string('P border');
            $table->string('P per');
            $table->string('P ket');
            $table->string('Wt min');
            $table->string('Wt max');
            $table->string('Wt border');
            $table->string('Wt per');
            $table->string('Wt ket');
            $table->string('Zn min');
            $table->string('Zn max');
            $table->string('Zn border');
            $table->string('Zn per');
            $table->string('Zn ket');
            $table->string('Soot min');
            $table->string('Soot max');
            $table->string('Soot border');
            $table->string('Soot per');
            $table->string('Soot ket');
            $table->string('Nit min');
            $table->string('Nit max');
            $table->string('Nit border');
            $table->string('Nit per');
            $table->string('Nit ket');
            $table->string('TAN min');
            $table->string('TAN max');
            $table->string('TAN border');
            $table->string('TAN per');
            $table->string('TAN ket');
            $table->string('Ca min');
            $table->string('Ca max');
            $table->string('Ca border');
            $table->string('Ca per');
            $table->string('Ca ket');
            $table->string('Fu min');
            $table->string('Fu max');
            $table->string('Fu border');
            $table->string('Fu per');
            $table->string('Fu ket');
            $table->string('TBN min');
            $table->string('TBN max');
            $table->string('TBN border');
            $table->string('TBN per');
            $table->string('TBN ket');
            $table->string('Ag min');
            $table->string('Ag max');
            $table->string('Ag border');
            $table->string('Ag per');
            $table->string('Ag ket');
            $table->string('Sn min');
            $table->string('Sn max');
            $table->string('Sn border');
            $table->string('Sn per');
            $table->string('Sn ket');
            $table->string('Pb min');
            $table->string('Pb max');
            $table->string('Pb border');
            $table->string('Pb per');
            $table->string('Pb ket');
            $table->string('Fe min');
            $table->string('Fe max');
            $table->string('Fe border');
            $table->string('Fe per');
            $table->string('Fe ket');
            $table->string('Cu min');
            $table->string('Cu max');
            $table->string('Cu border');
            $table->string('Cu per');
            $table->string('Cu ket');
            $table->string('Cr min');
            $table->string('Cr max');
            $table->string('Cr border');
            $table->string('Cr per');
            $table->string('Cr ket');
            $table->string('Al min');
            $table->string('Al max');
            $table->string('Al border');
            $table->string('Al per');
            $table->string('Al ket');
            $table->string('Si min');
            $table->string('Si max');
            $table->string('Si border');
            $table->string('Si per');
            $table->string('Si ket');
            $table->string('Na min');
            $table->string('Na max');
            $table->string('Na border');
            $table->string('Na per');
            $table->string('Na ket');
            $table->string('PI min');
            $table->string('PI max');
            $table->string('PI border');
            $table->string('PI per');
            $table->string('PI ket');
            $table->string('TI min');
            $table->string('TI max');
            $table->string('TI border');
            $table->string('TI per');
            $table->string('TI ket');
            $table->string('Sulf min');
            $table->string('Sulf max');
            $table->string('Sulf border');
            $table->string('Sulf per');
            $table->string('Sulf ket');
            $table->string('Mg min');
            $table->string('Mg max');
            $table->string('Mg border');
            $table->string('Mg per');
            $table->string('Mg ket');
            $table->string('Mo min');
            $table->string('Mo max');
            $table->string('Mo border');
            $table->string('Mo per');
            $table->string('Mo ket');
            $table->string('NAS 1638 min');
            $table->string('NAS 1638 max');
            $table->string('NAS 1638 border');
            $table->string('NAS 1638 per');
            $table->string('NAS 1638 ket');
            $table->string('V min');
            $table->string('V max');
            $table->string('V border');
            $table->string('V per');
            $table->string('V ket');
            $table->string('FP COC min');
            $table->string('FP COC max');
            $table->string('FP COC border');
            $table->string('FP COC per');
            $table->string('FP COC ket');
            $table->string('Wt D 95 min');
            $table->string('Wt D 95 max');
            $table->string('Wt D 95 border');
            $table->string('Wt D 95 per');
            $table->string('Wt D 95 ket');
            $table->string('Wt KF min');
            $table->string('Wt KF max');
            $table->string('Wt KF border');
            $table->string('Wt KF per');
            $table->string('Wt KF ket');
            $table->string('Gly min');
            $table->string('Gly max');
            $table->string('Gly border');
            $table->string('Gly per');
            $table->string('Gly ket');
            $table->string('TBN_D4739 min');
            $table->string('TBN_D4739 max');
            $table->string('TBN_D4739 border');
            $table->string('TBN_D4739 per');
            $table->string('TBN_D4739 ket');
            $table->string('PP min');
            $table->string('PP max');
            $table->string('PP border');
            $table->string('PP per');
            $table->string('PP ket');
            $table->string('Ni min');
            $table->string('Ni max');
            $table->string('Ni border');
            $table->string('Ni per');
            $table->string('Ni ket');
            $table->string('B min');
            $table->string('B max');
            $table->string('B border');
            $table->string('B per');
            $table->string('B ket');
            
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('condem');
    }
};
